[package]
name = "Civorum"
version = "0.1.0"
edition = "2024"

[dependencies]
map = { path = "crates/map" }
bevy = { version = "0.16" }

[workspace]
members = [
    ".",         # include root binary for now
    "crates/map",
]
resolver = "2"
